<MyGridLayout>
    #variable
    fname: first_name
    l_address: l_address
    age: age

    GridLayout:
        cols: 1
        size: root.width, root.height

        Label:
            text: "name"
            font_size: 20
        TextInput:
            multiline: False 

        Label:
            text:"Address-location"
            font_size: 20
        TextInput:
            multiline: False 
            font_size: 20   